version: '3.8'
services:
#  mail-dev:
#    container_name: mail-dev-bsn
#    image: maildev/maildev
#    ports:
#      - 1080:1080
#      - 1025:1025
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:26.0.6
    ports:
      - 8080:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - my-network
    command:
      - "start-dev"
  db:
    image: postgis/postgis:latest
    container_name: db
    environment:
      POSTGRES_DB: zikadashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypwd
    ports:
      - "5432:5432"
    volumes:
      - /c/Users/bajio/Desktop/Anjali/data:/tmp
    networks:
      - my-network

  spring-app:
    image: roadmaplearner/zikadashboard:v1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/zikadashboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mypwd
    depends_on:
      - db
    ports:
      - "9090:9090"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
